"""
Unified Strategy Engine for tick-by-tick processing.
Extracted and refactored from the Backtester class to work with live and historical data.
"""

from __future__ import annotations

# Standard library imports
import copy
from dataclasses import dataclass
from typing import List, Dict, Optional

# Third-party imports
import pandas as pd
import datetime as dt

# Local application imports
from unified_trading_platform.trading_core.utils import get_logger
from unified_trading_platform.trading_core.data_models import OrderAction, OrderType, TickData, Contract, SecurityType
from .config import StrategyConfig
from .strikes import select_strike
from .strategy_utils import (
    _hist_eod_ts,
    resolve_expiry_keyword,
    _reverse_position,
    _risk_from_any,
    _reentry_from_any,
    _hit_target,
    _hit_stop,
    _trail_stop,
    LiveLeg,
    PendingReEntry,
)

# Initialize logger
logger = get_logger(__name__)


@dataclass
class OrderSignal:
    """Represents a trading signal generated by the strategy engine"""

    action: OrderAction
    contract: Contract
    quantity: int
    price: Optional[float] = None
    order_type: OrderType = OrderType.MARKET
    leg_id: Optional[int] = None
    parent_leg_id: Optional[int] = None  # For re-entries
    comment: str = ""  # Optional comment about the signal
    signal_timestamp: Optional[dt.datetime] = None


__all__ = ["UnifiedStrategyEngine", "OrderSignal"]  # Export OrderSignal


class UnifiedStrategyEngine:
    """Unified strategy engine for tick-by-tick processing"""

    def __init__(self, strategy_config: StrategyConfig, exchange: str = "SMART", currency: str = "USD"):
        self.config = strategy_config
        self.exchange = exchange
        self.currency = currency
        self.live_legs: List[LiveLeg] = []
        self.pending_reentries: List[PendingReEntry] = []
        self.is_initialized = False
        self.entry_time = None
        self.exit_time = None
        self.current_date = None
        self.rows = []

    def initialize(self, current_date: dt.date, entry_time: str = None, exit_time: str = None):
        """Initialize the engine for a specific date and time range"""
        self.current_date = current_date
        self.entry_time = entry_time or self.config.entry_time
        self.exit_time = exit_time or self.config.exit_time
        self.is_initialized = True

        # Initialize legs based on strategy config
        self._initialize_legs()

    def _initialize_legs(self):
        """Initialize strategy legs for the current date"""
        for i, leg_spec in enumerate(self.config.legs, 1):
            # Resolve expiry date
            exp_date = resolve_expiry_keyword(self.current_date, leg_spec.expiry)

            # For now, we'll need market data to select strikes
            # This will be called again when we have the first tick
            leg = LiveLeg(
                leg_id=i,
                spec=leg_spec,
                strike=0.0,  # Will be set when we have market data
                qty=int(leg_spec.qty_lots) * int(self.config.lot_size),
            )
            leg.expiry_date = exp_date
            leg.exit_px = 0.0
            leg.exit_ts = None
            self.live_legs.append(leg)

    @staticmethod
    def _lookup_premium(option_chain: Optional[pd.DataFrame], strike: float, option_type: str) -> Optional[float]:
        """Look up option premium from chain DF by strike + option_type.
        Works identically for both backtest (H5-sourced) and live (broker-sourced) chains."""
        if option_chain is None or option_chain.empty:
            return None
        row = option_chain[(option_chain["strike"] == strike) & (option_chain["option_type"] == option_type.upper())]
        if row.empty:
            return None
        return float(row.iloc[0]["price"])

    def process_tick(
        self, tick_data: TickData, underlying_price: float, option_chain: Optional[pd.DataFrame] = None
    ) -> List[OrderSignal]:
        """Process a single tick and return order signals"""
        if not self.is_initialized:
            raise RuntimeError("Engine not initialized. Call initialize() first.")

        signals = []
        # Check for new entries (if we haven't entered yet)
        if not self._has_entered():
            entry_signals = self._check_entry_conditions(tick_data, underlying_price, option_chain)
            signals.extend(entry_signals)

        # Check for exits on existing positions
        exit_signals = self._check_exit_conditions(tick_data, underlying_price, option_chain)
        signals.extend(exit_signals)

        # Check for re-entries
        reentry_signals = self._check_reentry_conditions(tick_data, underlying_price, option_chain)
        signals.extend(reentry_signals)

        # Update current positions with new tick data
        self._update_positions_with_tick(tick_data, underlying_price, option_chain)
        return signals

    def _has_entered(self) -> bool:
        """Check if we have any open positions"""
        return any(leg.entry_ts is not None for leg in self.live_legs)

    def generate_signal_for_leg(self, leg: LiveLeg):
        # Create order signal
        contract = Contract(
            symbol=f"{leg.spec.option_type}{leg.strike}",
            security_type=SecurityType.OPTION,
            exchange=self.exchange,
            currency=self.currency,
            expiry=leg.expiry_date.strftime("%Y%m%d"),
            strike=leg.strike,
            option_right=leg.spec.option_type,
            multiplier=str(self.config.lot_size),
        )

        action = OrderAction.BUY if leg.spec.position.lower().startswith("buy") else OrderAction.SELL

        signal = OrderSignal(action=action, contract=contract, quantity=leg.qty, leg_id=leg.leg_id)
        return signal

    def _check_entry_conditions(
        self, tick_data: TickData, underlying_price: float, option_chain: Optional[pd.DataFrame]
    ) -> List[OrderSignal]:
        """Check if entry conditions are met"""
        signals = []

        if option_chain is None:
            return signals  # Need option chain for entry

        for leg in self.live_legs:
            logger.info(f"Checking entry conditions for leg: {leg}")
            if leg.entry_ts is not None:
                continue  # Already entered

            # Select strike based on current market conditions
            exp_date = resolve_expiry_keyword(tick_data.timestamp.date(), leg.spec.expiry)
            snap = option_chain[
                (option_chain["expiry"] == exp_date) & (option_chain["option_type"] == leg.spec.option_type.upper())
            ]
            strike = select_strike(snap, leg.spec.option_type.upper(), underlying_price, leg.spec.strike_criteria)
            if strike is None:
                continue

            leg.strike = strike
            leg.signal_timestamp = tick_data.timestamp

            signals.append(self.generate_signal_for_leg(leg))

            leg.entry_ts = tick_data.timestamp
            # Use option premium from chain; fall back to tick price only if chain unavailable
            option_premium = self._lookup_premium(option_chain, strike, leg.spec.option_type)
            leg.entry_px = (
                option_premium
                if option_premium is not None
                else (tick_data.close or tick_data.last or tick_data.bid or tick_data.ask)
            )
            leg.entry_S = underlying_price
            leg.best_fav_px = leg.entry_px
            logger.info(
                f"Leg {leg.leg_id} entered: {leg.spec.position} {leg.spec.option_type}@{strike} premium={leg.entry_px:.2f} underlying={underlying_price:.2f}"
            )

        return signals

    def _check_exit_conditions(
        self, tick_data: TickData, underlying_price: float, option_chain: Optional[pd.DataFrame] = None
    ) -> List[OrderSignal]:
        """Check if exit conditions are met for existing positions"""
        signals = []

        for leg in self.live_legs:
            if leg.entry_ts is None or leg.exit_ts is not None:
                continue  # Not entered or already exited

            # Use option premium from chain; fall back to tick price if unavailable
            option_premium = self._lookup_premium(option_chain, leg.strike, leg.spec.option_type)
            current_price = (
                option_premium
                if option_premium is not None
                else (tick_data.close or tick_data.last or tick_data.bid or tick_data.ask)
            )
            if current_price is None:
                continue

            # Update PnL
            mult = -1 if leg.spec.position.lower().startswith("sell") else 1
            leg.pnl = (current_price - leg.entry_px) * mult * leg.qty

            # Update best favorable price for trailing
            if leg.best_fav_px is None:
                leg.best_fav_px = leg.entry_px
            if mult == -1:  # short: favorable is price down
                leg.best_fav_px = min(leg.best_fav_px, current_price)
            else:  # long: favorable is price up
                leg.best_fav_px = max(leg.best_fav_px, current_price)

            # Check risk rules
            rc = _risk_from_any(leg.spec.risk)
            should_exit = False
            exit_reason = None
            logger.debug(
                "rc=%s, leg_spec=%s, entry_px=%s, entry_S=%s, current_premium=%s, underlying=%s",
                rc,
                leg.spec,
                leg.entry_px,
                leg.entry_S,
                current_price,
                underlying_price,
            )

            if _hist_eod_ts(tick_data, self.config.exit_time):
                should_exit = True
                exit_reason = "EOD"
                leg.hit_target = True
            if _hit_target(rc.target, leg.spec.position, leg.entry_px, leg.entry_S, current_price, underlying_price):
                should_exit = True
                exit_reason = "TARGET"
                leg.hit_target = True
            elif _hit_stop(rc.sl, leg.spec.position, leg.entry_px, leg.entry_S, current_price, underlying_price):
                should_exit = True
                exit_reason = "SL"
                leg.hit_sl = True
            elif _trail_stop(rc.trail, leg.spec.position, leg.best_fav_px, current_price):
                should_exit = True
                exit_reason = "TRAIL"
                leg.hit_trail = True

            if should_exit:
                signals.append(self.generate_signal_for_leg(leg))

                # Mark as exited — in forward mode, this should be updated from actual fill
                leg.exit_ts = tick_data.timestamp
                leg.exit_px = current_price
                leg.exit_reason = exit_reason

                # Check for re-entries
                if exit_reason in ("SL", "TARGET"):
                    self._spawn_or_queue_reentry(tick_data.timestamp, leg, exit_reason)
        return signals

    def _check_reentry_conditions(
        self, tick_data: TickData, underlying_price: float, option_chain: Optional[pd.DataFrame]
    ) -> List[OrderSignal]:
        """Check pending re-entries"""
        signals = []
        new_pending = []

        # fixme: should this return empty signal list or try fetching option_chain?
        if option_chain is None:
            return signals

        for pen in self.pending_reentries:
            exp_date = resolve_expiry_keyword(self.current_date, pen.spec.expiry)
            strike = select_strike(
                option_chain, pen.spec.option_type.upper(), underlying_price, pen.spec.strike_criteria
            )
            if strike is not None:
                # Create new leg
                new_leg = LiveLeg(
                    leg_id=len(self.live_legs) + 1,
                    spec=pen.spec,
                    strike=strike,
                    qty=int(pen.spec.qty_lots) * int(self.config.lot_size),
                )
                new_leg.expiry_date = exp_date
                new_leg.entry_ts = tick_data.timestamp
                # Use option premium from chain for re-entry price
                option_premium = self._lookup_premium(option_chain, strike, pen.spec.option_type)
                new_leg.entry_px = (
                    option_premium
                    if option_premium is not None
                    else (tick_data.close or tick_data.last or tick_data.bid or tick_data.ask)
                )
                new_leg.entry_S = underlying_price
                new_leg.best_fav_px = new_leg.entry_px
                new_leg.parent_leg_id = pen.parent_leg_id
                new_leg.strike = strike

            mode = pen.mode
            if mode.startswith("RE_ASAP") or mode == "LAZY_LEG":
                self.live_legs.append(new_leg)
                signals.append(self.generate_signal_for_leg(new_leg))
                continue

            elif mode.startswith("RE_COST"):
                # Cost-based re-entry
                current_price = tick_data.close or tick_data.last or tick_data.bid or tick_data.ask
                ok = (
                    (current_price >= pen.watch_price)
                    if pen.spec.position == "Buy"
                    else (current_price <= pen.watch_price)
                )
                if ok:
                    self.live_legs.append(new_leg)
                    signals.append(self.generate_signal_for_leg(new_leg))
                    continue

            elif mode.startswith("RE_MOMENTUM"):
                # Momentum-based re-entry
                pts = float(self.config.overall_momentum.get("points", 0.0))
                if pts > 0:
                    current_price = tick_data.close or tick_data.last or tick_data.bid or tick_data.ask
                    if current_price >= (pen.watch_price + pts):  # fixme: the condition should be based on long/short
                        self.live_legs.append(new_leg)
                        signals.append(self.generate_signal_for_leg(new_leg))
                        continue
            else:
                new_pending.append(pen)
        self.pending_reentries = new_pending
        return signals

    def _spawn_or_queue_reentry(self, timestamp: pd.Timestamp, leg: LiveLeg, reason: str):
        """Spawn or queue a re-entry based on leg configuration"""
        rule = _reentry_from_any(leg.spec.reentry_on_sl if reason == "SL" else leg.spec.reentry_on_target)

        if not (rule and getattr(rule, "enabled", False)):
            return

        if rule.max_count <= 0:
            return

        # Enforce caps
        if reason == "SL" and leg.re_sl_count >= min(20, rule.max_count):
            return
        if reason == "TARGET" and leg.re_tgt_count >= min(20, rule.max_count):
            return

        # Respect no_reentry_after
        if self.config.no_reentry_after:
            cutoff = pd.Timestamp.combine(self.current_date, dt.time.fromisoformat(self.config.no_reentry_after))
            if timestamp >= cutoff:
                return

        mode = str(rule.mode).upper()
        if mode.endswith("_REV"):
            new_pos = _reverse_position(leg.spec.position)
        else:
            new_pos = leg.spec.position

        # Create spec for re-entry
        spec = copy.deepcopy(leg.spec)
        spec.position = new_pos

        if mode == "LAZY_LEG" and isinstance(rule.lazy_leg, dict):
            # Convert dict to LegSpec (simplified)
            spec = leg.spec  # Use original for now

        # Create pending re-entry
        pen = PendingReEntry(
            parent_leg_id=leg.leg_id,
            trigger=reason,
            mode=mode,
            created_ts=timestamp,
            spec=spec,
            watch_strike=(leg.strike if mode.startswith("RE_COST") else None),
            watch_price=leg.entry_px,
        )

        self.pending_reentries.append(pen)

        # Update counters
        if reason == "SL":
            leg.re_sl_count += 1
        else:
            leg.re_tgt_count += 1

    def _update_positions_with_tick(
        self, tick_data: TickData, underlying_price: float, option_chain: Optional[pd.DataFrame] = None
    ):
        """Update position per tick — only records rows for legs that have been entered.
        For open legs, uses current option premium; for closed legs, uses exit_px."""
        for leg in self.live_legs:
            if leg.entry_ts is None:
                continue  # Skip legs that haven't entered yet

            mult = -1 if leg.spec.position.lower().startswith("sell") else 1
            # For open legs, look up current option premium; for closed legs, use exit_px
            if leg.exit_ts is not None:
                price_for_pnl = leg.exit_px
            else:
                option_premium = self._lookup_premium(option_chain, leg.strike, leg.spec.option_type)
                price_for_pnl = (
                    option_premium if option_premium is not None else (tick_data.close or tick_data.last or 0.0)
                )

            pnl_per_unit = (price_for_pnl - leg.entry_px) * mult
            pnl = pnl_per_unit * leg.qty

            cost_roundtrip = 0  # placeholder for now
            lot_size = 1  # placeholder for now
            slippage_per_fill = 0  # placeholder for now
            costs = (cost_roundtrip * (leg.qty / lot_size)) + slippage_per_fill
            pnl_net = pnl - costs
            self.rows.append(
                {
                    "date": str(tick_data.timestamp),
                    "index": tick_data.symbol,
                    "leg_id": leg.leg_id,
                    "position": leg.spec.position,
                    "option_type": leg.spec.option_type,
                    "expiry": str(leg.expiry_date),
                    "strike": leg.strike,
                    "qty": leg.qty,
                    "entry_ts": leg.entry_ts,
                    "exit_ts": leg.exit_ts,
                    "entry_price": leg.entry_px,
                    "exit_price": price_for_pnl,
                    "underlying_price": underlying_price,
                    "pnl": round(pnl, 2),
                    "pnl_after_cost": round(pnl_net, 2),
                    "hit:sl": leg.hit_sl,
                    "hit:target": leg.hit_target,
                    "exit_reason": (
                        leg.exit_reason or ("SL" if leg.hit_sl else ("TARGET" if leg.hit_target else "TIME"))
                    ),
                }
            )

    def get_current_positions(self) -> List[LiveLeg]:
        """Get current live positions"""
        return [leg for leg in self.live_legs if leg.entry_ts is not None and leg.exit_ts is None]

    def get_all_positions(self) -> List[LiveLeg]:
        """Get all positions (including closed ones)"""
        return self.live_legs

    def update_position_on_fill(self, leg_id: int, fill_info: Dict):
        """Update position when an order is filled"""
        for leg in self.live_legs:
            if leg.leg_id == leg_id:
                # Update leg with fill information
                if fill_info.get("action") == "entry":
                    leg.entry_ts = pd.Timestamp(fill_info.get("timestamp"))
                    leg.entry_px = fill_info.get("price")
                    leg.entry_S = fill_info.get("underlying_price")
                    leg.best_fav_px = leg.entry_px
                elif fill_info.get("action") == "exit":
                    leg.exit_ts = pd.Timestamp(fill_info.get("timestamp"))
                    leg.exit_px = fill_info.get("price")
                    # leg.exit_reason = fill_info.get('reason', 'FILLED')
                break

    def should_exit(self, current_time: dt.time) -> bool:
        """Check if we should exit based on time"""
        if not self.exit_time:
            return False

        exit_time = dt.time.fromisoformat(self.exit_time)
        return current_time >= exit_time

    def get_portfolio_summary(self) -> Dict:
        """Get current portfolio summary"""
        total_pnl = sum(leg.pnl for leg in self.live_legs if leg.entry_ts is not None)
        open_positions = len(self.get_current_positions())
        closed_positions = len([leg for leg in self.live_legs if leg.exit_ts is not None])

        return {
            "total_pnl": total_pnl,
            "open_positions": open_positions,
            "closed_positions": closed_positions,
            "total_positions": len(self.live_legs),
            "pending_reentries": len(self.pending_reentries),
        }
